### ISSUE TITLE
17th 9:00 Orientation for new HR admin stuff, Bojan

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/recruitment#17]
https://github.com/timeriver/recruitment/issues/19#issue-390212321

**Comment by writerityyuko** [comment]
@writerity-watanabe 

月曜日からBojanが来ますが、
仕事を始めるにあたって、PCの設定や、ツールの説明、および、
具体的な業務について説明をしようと思っていますが、
渡邊さんは午前中はお忙しそうなので、ひとまず私と、
必要に応じてエレナのほうから説明、ということでよいでしょうか？

**Comment by writerity-watanabe** [comment]
@writerityyuko 
はい、よろしくお願いします！

契約書を準備している間に、必要なアカウントを作成させて、各種設定など済ませるようにしましょう。そんなにパンパンに仕事がないときはエレナのタスクを振るorライタリティのブログを書いてもらったりしましょう（ライタリティの宣伝の一環として）

**Comment by writerityyuko** [comment]
@writerity-watanabe 
承知しましたー。
