### ISSUE TITLE
Draft contract with HR-admin, Bojan

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/recruitment#18]
Since new HR admin Bojan start his work on next Monday, could you draft the contract paper?

The condition is below,
- 180MKD/hour, 20 hours per week
- 9:00~13:00, Monday to Friday
- Start on 17th Dec
- duration: 6 month. But after 3 months,  be negotiable for renewal contract.

**Comment by writerityelena** [comment]
@writerityyuko Position: 
Administrative and HR Assistant ?

**Comment by writerityyuko** [comment]
@writerityelena 

Please write position name as Administrator this time.

**Comment by writerityelena** [comment]
[Bojan T Engagement Contract .pdf](https://github.com/timeriver/recruitment/files/2676582/Bojan.T.Engagement.Contract.pdf)
@writerityyuko @writerity-watanabe
