### ISSUE TITLE
18th(Tue) 13:00 Interview-Englsih teacher w/Sinolicka

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/recruitment#23]

**Comment by writerityyuko** [comment]
@writerity-watanabe 

明日、英語の先生の面接が1件入っているんですが、同席されますか？

**Comment by writerity-watanabe** [comment]
@writerityyuko 
面接はお任せします！

**Comment by writerityyuko** [comment]
@writerity-watanabe 
本日面接したSinolickaさんについてご報告です。

‐英語レベルに関する証明書/資格がない
-教師経験は2年で、プライベートでの子供2人に教えているくらい
- 英語は比較的きれい

ということで、ちょっと今回のポジションには物足りないという感じなので、
少し時間をおいて、お断りする方向です。
（ほかの候補者を可能な限り見てから返事をしたいと思っているので、すぐには連絡しません。）

**Comment by writerity-watanabe** [comment]
@writerityyuko 
了解です！
