### ISSUE TITLE
Bojan (HR-admin) mtg at 10th(Mon) 13:00

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/recruitment#7]

**Comment by writerityyuko** [comment]
来週月曜日の話し合いで、最終的な契約内容の結論を出したいと思います。

今のところ、
180MKDで、engagement contract 6 month、20時間/週とオファーしていますが、
契約期間を短くしたいかも、といったことをおっしゃってました。

**Comment by writerity-watanabe** [comment]
@writerityyuko 
了解です！
１〜２ヶ月とかだとリスクもあるので（特に１ヶ月だと嫌なら契約終了、すぐに辞められてしまうとただの無駄金になる）少し給与は交渉したいと思っています。
その期間だけ150MKDにして、３ヶ月目以降も続行なら180MKDで新たな契約（3ヶ月）を約束するなど
