### ISSUE TITLE
Bojan (HR-admin) making contract

### ISSUE THREAD

**Issue by writerityyuko** [timeriver/recruitment#9]

**Comment by writerityyuko** [comment]
@writerity-watanabe 
今日か明日にBojan2号の契約書のドラフトをエレナに作ってもらいたいのですが、デニから何かコメントありましたか？

**Comment by writerity-watanabe** [comment]
@writerityyuko 
今朝メールはまだ来ていなかったので、
これから聞こうと思います！
少々お待ちください。

**Comment by writerityyuko** [comment]
@writerity-watanabe 
了解ですー。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

承知しました。それではBojan2号について、契約書のドラフト作成をエレナに依頼しますね。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

Bojan2号の契約書作成で、
ポジション名は、Administratorでよいですか？
（エレナの契約書名は、Administrative workerとなっているらしいのですが、
workerというのが、若干ひっかかりを感じるもので。。）

**Comment by writerity-watanabe** [comment]
@writerityyuko 
特に指定していないので、大丈夫です！
HR assistantなど入れても入れなくても良いです。

**Comment by writerityyuko** [comment]
@writerity-watanabe 

はーい。承知しました。一応、Administratorだけにして、本人がなんか言ってきたら、HRとか入れますー。

**Comment by writerityyuko** [comment]
[Bojan.T.Engagement.Contract.pdf](https://github.com/timeriver/recruitment/files/2679109/Bojan.T.Engagement.Contract.pdf)

**Comment by writerity-watanabe** [comment]
@writerityyuko @writerityelena 
軽く確認したところです。
細かくは見れていません。

remove
5.3 
5.4
6.7

check again
why 14 days 
14.3
14.6

about "business trip" 
we need this in contract?
for what?
4.3
6.8

**Comment by writerityyuko** [comment]
@writerityelena 

My comment about the draft is same as Hide did.
So, could you modify the draft on Monday?

**Comment by writerity-watanabe** [comment]
@writerityelena 
okay checked

**Comment by writerityelena** [comment]
@writerity-watanabe 
i can print right?
